IF OBJECT_ID('tempdb..#ESPACO_DATABASES') IS NOT NULL
	DROP TABLE #ESPACO_DATABASES
CREATE TABLE #ESPACO_DATABASES (
	 DRIVE CHAR(1)
	,TAMANHO_ARQUIVO DECIMAL(15, 2)
	,ESPACO_UTILIZADO DECIMAL(15, 2)
	,ESPACO_LIVRE DECIMAL(15, 2)
	,ARQUIVO VARCHAR(100)
	,CAMINHO_ARQUIVO VARCHAR(255)
	)
INSERT INTO #ESPACO_DATABASES
EXEC master.sys.sp_MSforeachdb ' USE [?];
   SELECT  SUBSTRING(A.FILENAME, 1, 1) AS DRIVE
	  ,CONVERT(DECIMAL(12, 2), ROUND(A.SIZE / 128.000, 2)) AS TAMANHO_ARQUIVO
	  ,CONVERT(DECIMAL(12, 2), ROUND(FILEPROPERTY(A.NAME, ''SPACEUSED'') / 128.000, 2)) AS ESPACO_UTILIZADO
	  ,CONVERT(DECIMAL(12, 2), ROUND((A.SIZE - FILEPROPERTY(A.NAME, ''SPACEUSED'')) / 128.000, 2)) AS ESPACO_LIVRE
	  ,A.NAME AS ARQUIVO
	  ,A.FILENAME AS CAMINHO_ARQUIVO
	FROM dbo.sysfiles A
	ORDER BY ARQUIVO
		,DRIVE
   '
SELECT *
FROM #ESPACO_DATABASES


/*
--Liberar tempdb

DBCC FREEPROCCACHE
GO
DBCC DROPCLEANBUFFERS
go
DBCC FREESYSTEMCACHE ('ALL')
GO
DBCC FREESESSIONCACHE
GO
*/
