--SCRIPT PARA BACKUP
BACKUP DATABASE [database]
TO DISK = ''
WITH COMPRESSION, CHECKSUM,  STATS =1

--SCRIPT PARA BACKUP DIFF
BACKUP DATABASE [database]
TO DISK = ''
WITH DIFFERENTIAL, COMPRESSION, CHECKSUM,  STATS =1